### ISSUE TITLE
No error handling for when track lyric is not found 

### ISSUE THREAD

**Issue by meeday** [meeday/The-Music-App#137]
some lyrics work some lyrics are not found but show lyrics from your previous search
![image](https://user-images.githubusercontent.com/59993824/81404080-a15c7100-912c-11ea-8a8b-17ba7189fb6a.png)

**Comment by Goldenaries658** [comment]
Needs to have a brief summary as a title, where the problem is happening (branch/page), a description of the problem, how to reproduce it and screenshots, link it to milestone and project and assign labels.

**Comment by meeday** [comment]
I was testing dragos branch in the pull request. Search for dave psycho lyrics

**Comment by Goldenaries658** [comment]
Error was due to an unused variable that sometimes returned undefined, deleted the variable which has fixed the problem
