### ISSUE TITLE
Dynamically change background to album cover art/random images related to artist

### ISSUE THREAD

**Issue by Goldenaries658** [meeday/The-Music-App#27]
Feature discussion

**Comment by meeday** [comment]
I like that idea definitely something that can be done after the MVP has been complete

**Comment by meeday** [comment]
I played around with this and the images are not big enough to cover the background so they appear blurred and stretched I even tried with pictures from a different api and the results varied it reduces the quality of our app

**Comment by meeday** [comment]
this will make our app look tacky as we can't get images big enough for the background
