### ISSUE TITLE
link the seatGeek API info to the html components in artist result page

### ISSUE THREAD

**Issue by drg0drg** [meeday/The-Music-App#52]

**Comment by Goldenaries658** [comment]
What's the plan with this?

**Comment by drg0drg** [comment]
If we were to implement seatGeek API to show a short list of following concerts on artist page - need to agree on implementation. Where exactly, how to be displayed and what should the user experience be. Probably the list can be made clickable to carry user to a ticket store, but probably we'll have to keep it simple for now.

**Comment by drg0drg** [comment]
seatGeek API response structure is comprised of (what we can use): 
datetime_local --> date/hour of concert
short_title --> name of concert and type--> type of gig (concert/festival/etc)
url --> seatgeek link for the specific concert (diagram of seats - so probably tickets can be bought directly from seatGeek)
venue --> big object from which we can select name--> name of the venue, city, country
