### ISSUE TITLE
investigate lyrics API to add features on the App

### ISSUE THREAD

**Issue by drg0drg** [meeday/The-Music-App#54]
musixmatch is free but allows 30% access only.

used audd.io:
https://api.audd.io/findLyrics/?q=adele hello&api_token=" 
meeda's token 56504f66202634311b0e5c04f32ced06

dragos' token: 
 5f4c7ca039f99affbd2571ed749f2ddc

**Comment by Goldenaries658** [comment]
You've moved this to completed. What's completed? I don't see anything and the issue is still open. You need to write everything in the issue if it doesn't have a pull request attached.

What api are you using, what were your findings, how can we use it, limitations? etc etc etc

**Comment by drg0drg** [comment]
Used Audd.io. 
The inputs are track name and artist name. We can get both from LastFM api to fill the <li> in the track  response page. By ''reading" the list items we can call Audd-io API to get the lyrics.

Audd.io API response structure is comprised of artist name, track name, IDs for both and lyrics. 

For showing the lyrics in the modal, we use track name+ artist name as title and the lyrics for content. 

Limitations - we had to purchase a paid plan to have access to 1000 calls/month.
Advantages - the response also features links to apple music, spotify and youtube. This can be further explored on following launches to present the user with embedded youtube video for each search.
